name: CI Pipeline

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Check Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Train And Upload Model On HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN} }
        if: contains(steps.changed-files.outputs.all_changed_files, 'src/') || contains(steps.changed-files.outputs.all_changed_files, 'data/')
        run: |
          huggingface-cli login --token $HF_TOKEN
          python src/train.py

      - name: Run tests
        run: pytest tests/

  build-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t amosdisabatino/mlops_project:latest .

      - name: Log In To DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Image
        run: docker push amosdisabatino/mlops_project:latest
