name: Model Training Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "src/train.py"
      - "pyproject.toml"
      - ".github/workflows/train.yml"

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
  
      - name: Install Dependencies
        run: |
            pip install --upgrade pip
            pip install -e .
            pip install datasets transformers evaluate
  
      - name: Run Training Script
        run: |
          python src/train.py
  
      - name: Upload Training Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: finetuned-model
          path: |
            models/finetuned_model/
            logs/training.log
